<!--suppress MsbuildTargetFrameworkTagInspection -->
<Project>
    <PropertyGroup>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <UseArtifactsOutput>true</UseArtifactsOutput>
    </PropertyGroup>
</Project>
