<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);CA1707;CA1822;CA1852;CA1812;CA1515</NoWarn>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup Label="References">
        <ProjectReference Include="..\Dubzer.WhatwgUrl.Tests\Dubzer.WhatwgUrl.Tests.csproj" />
        <ProjectReference Include="..\Dubzer.WhatwgUrl\Dubzer.WhatwgUrl.csproj" />
        <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Dubzer.WhatwgUrl.Tests\Resources\*.*">
            <Link>.\Resources\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>