<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<NoWarn>$(NoWarn);CA1062;CA1054;CA1515</NoWarn>
	</PropertyGroup>

	<ItemGroup Label="References">
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="Verify.XunitV3" Version="31.7.3" />
		<PackageReference Include="xunit.v3.mtp-v2" Version="3.2.1" />
		<ProjectReference Include="..\Dubzer.WhatwgUrl\Dubzer.WhatwgUrl.csproj" />
	</ItemGroup>

	<ItemGroup Label="Resources">
		<None Update="Resources\IdnaTestV2.json" CopyToOutputDirectory="PreserveNewest" />
		<None Update="Resources\urltestdata.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
