name: 'Pushed'

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: 'Build and run tests for ${{ matrix.configuration }}'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-dotnet@v4'
        with:
          dotnet-version: '8.x'
      - name: 'Run tests'
        run: dotnet test -c ${{ matrix.configuration }}
