name: 'Release'
run-name: 'Publish release ${{ github.event.release.tag_name }} to NuGet'

permissions:
  contents: read
  packages: write

on:
  release:
    types: ['created']

jobs:
  publish:
    name: 'Build and publish to the package repository'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-dotnet@v4'
        with:
          dotnet-version: '8.x'
      - name: 'Replace resources in README.md'
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          replacement-text: '(https://raw.githubusercontent.com/Dubzer/Dubzer.WhatwgUrl/${{ github.event.release.tag_name }}/docs/resources'
          search-text: '(docs/resources'
      - name: 'Replace relative links to docs with absolute ones'
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          replacement-text: '(https://github.com/Dubzer/Dubzer.WhatwgUrl/tree/${{ github.event.release.tag_name }}/docs/'
          search-text: '(docs/'
      - name: 'Build package'
        run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes=${{ github.event.release.html_url }} /p:RepositoryUrl=${{ github.event.repository.html_url }}
      - name: 'Add Github NuGet source'
        run: dotnet nuget add source --username Dubzer --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Dubzer/index.json"
      - name: 'Publish package to Github Packages'
        run: dotnet nuget push -s github --api-key ${{ secrets.GITHUB_TOKEN }} artifacts/package/release/*.nupkg
      - name: 'Publish package to NuGet'
        run: dotnet nuget push -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} artifacts/package/release/*.nupkg